blog/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog.Data.Models;
using blog.Mappers;
using blog.Models;
using blog.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace blog.Controllers
{
    public class ArticleController : Controller
    {
        private IArticleService articleService;
        private IMapper<ArticleViewModel, Article> articleMapper;

        public ArticleController(IArticleService articleService, IMapper<ArticleViewModel, Article> articleMapper)
        {
            this.articleService = articleService;
            this.articleMapper = articleMapper;
        }

        public async Task<IActionResult>Details(int id)
        {
            var article = await this.articleService.FindArticleById(id);
            var model = this.articleMapper.Map(article);
            return View(model);
        }
    }
}

blog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using blog.Models;
using blog.Services.Contracts;
using blog.Mappers;
using blog.Data.Models;
using Microsoft.Extensions.Caching.Memory;
using blog.Extensions;

namespace blog.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly IMemoryCache cache;
        private IArticleService articleService { get; set; }
        private ITagService tagService { get; set; }
        private IMapper<AllArticlesViewModel, List<Article>> allArticlesMapper{ get; set; }

        private const int onPage=3;
        private TimeSpan span = TimeSpan.FromMinutes(40);

        public HomeController(IArticleService articleService,
            ITagService tagService,
            IMapper<AllArticlesViewModel, List<Article>> allArticlesMapper,
            IMemoryCache cache)
        {
            this.articleService = articleService;
            this.tagService = tagService;
            this.allArticlesMapper = allArticlesMapper;
            this.cache = cache;
        }


        public async Task<IActionResult> Index(string id,int page=1)
        {
            List<string> titles = null;
            List<Tag> tags = null;
            ViewBag.MenuBar = "Search";
            
            if (cache.Get("Titles") == null)
            {
                titles =await this.articleService.ListTitles();
                cache.Set("Titles", titles, span);
            }
            if (cache.Get("Tags") == null)
            {
                tags = await this.tagService.ListAllTags();
                this.cache.Set("Tags", tags, span);
            }
            titles = cache.Get<List<string>>("Titles");
            tags = cache.Get<List<Tag>>("Tags");
            var tagNames = tags.Select(t => t.Name).ToList();
            var articles = await this.articleService.ListArticles(page-1,onPage,id);
            AllArticlesViewModel model = new AllArticlesViewModel() ;
            if (articles != null)
            {

                model = this.allArticlesMapper.Map(articles.Item2);
                model.PagingModel = new PagingViewModel()
                {
                    CurrPage = page,
                    Pages = articles.Item1.GetPages(onPage),
                    IdRoute = id,
                };
            }
            model.Tags = tagNames;
            model.Titles = titles;
            model.Test = id;
            
            return View(model);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

blog/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

blog/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

blog/Views/Home/Index.cshtml
@inject UserManager<ApplicationUser> UserManager
@model AllArticlesViewModel
@{
    ViewData["Title"] = "Index";
}

@if (User.IsInRole("Admin"))
{
    <div style="margin:20px auto 20px;text-align:center">
        <a asp-area="Admin" asp-controller="Article" asp-action="CreateArticle" class="btn btn-primary" style="width:80%">CREATE NEW ARTICLE</a>
    </div>
}

@foreach (var item in Model.Titles)
{
    <div class="titles" style="display:none">@item</div>
}
@foreach (var item in Model.Tags)
{
    <div class="tags" style="display:none">@item</div>
}
<div style="background-color:lightgrey;text-align:center">
    <span style="font-size: 20px">Articles </span>
    @if (!string.IsNullOrEmpty(@Model.PagingModel.IdRoute))
    {
        <span style="font-size: 12px">(Filter: @Model.PagingModel.IdRoute.Substring(5))</span>
    }

</div>
<div class="container body-content" style="min-height:300px">
    @if (Model.ArticleModels != null)
    {
        @foreach (var item in Model.ArticleModels)
        {
            <div>
                <h3>@item.Title </h3><span>(created by: <b>@item.CreatedByName</b>; </span><span>last edited by: <b>@item.LastEditedByName </b>on <b>@item.LastEditedOn.ToString("dd.MM.yyyy, HH:mm")</b>)</span>
                @if (item.Tags != null && item.Tags.Count > 0)
                {<p>
                        <span>Tags: </span>
                        @foreach (var tag in item.Tags)
                        {
                            <span>
                                <b><a asp-controller="Home" asp-action="Index" asp-route-id=@("_tag_"+tag.Name) asp-route-page="1">[@tag.Name]</a></b>
                            </span>

                        }
                    </p>
                }
                <p>
                    @item.Content.Substring(0, Math.Min(item.Content.Length, 100))

                    <span>
                        <a asp-area="" asp-controller="Article" asp-action="Details" asp-route-id=@item.Id>
                            @if (item.Content.Length > 100)
                            {
                                <text>...Read more...</text>
                            }
                            else
                            {
                                <text>...Details...</text>
                            }
                        </a>
                    </span>
                </p>
                <hr />
            </div>
        }
    }
    else
    {
        <h3>No articles found</h3>
    }
</div>
@if (Model.PagingModel != null && Model.PagingModel.Pages > 0)
{
    <div style="background-color:lightgrey;margin:0;width:100%;padding:0">
        @await Html.PartialAsync("_PagingPartial", @Model.PagingModel)
    </div>
}